### PR TITLE
Create Idimkova-Monetizing-online-advertisements

### PR DESCRIPTION
**Pull request by idimkova**

### CODE REVIEW

**Comment by mlong505** [comment]
:+1: I'm glad you mentioned the advertising lecture, @idimkova. I had little background in this, and I was interested to learn how Google's near-monopoly works. I feel like there is a lot of room for new services like the one you mentioned that help advertisers get more transparency about how they bid and where their ads are eventually displayed.

**Comment by ezehnal** [comment]
Good takeaway @idimkova - the advertising revenue model is certainly something that anyone interested in digital commerce should be aware of. I think the targeted vs. broad advertising approach that James mentioned in class really highlighted to me how well ads can be targeted online - impressive.

As for the content, for me it appears on 2 lines, it may make sense to word wrap your content so it's a bit easier to read. 

Good takeaway :+1:

**Comment by chencbs** [comment]
@idimkova agree with Evan on needing to wrap your content. 

There was an interesting article in the WSJ about this last month discussing how some publishers have been avoiding automated ad sales to provide a higher quality experience to visitors and "cut out the middlemen". I was surprised to learn that the publishers typically get less than 50% of the revenue generated by exchanges. 

In case anyone is interested:
http://www.wsj.com/articles/publishers-that-say-no-to-automated-ad-sales-1443650792

**Comment by brookeabunnell** [comment]
@idimkova great points! I was watching CNBC a few weeks ago, around the time Apple iOS 9 came out. Apparently new iOS 9 functionality allowed users to download ad blockers from the app store for the first time. Analysts were saying this was Apple's way of sending Google a message that its competitive advantage is coming to an end. Here's an article about it: http://www.theguardian.com/technology/2015/sep/17/adblockers-ios-9-app-charts-peace

LGMT :+1:

**Comment by idimkova** [comment]
Thanks for the feedback re: content spacing.  I will make sure I put all the text on one line next time.

I really enjoyed reading the WSJ and Guardian articles.  Thanks for posting @chencbs and @brookeabunnell

**Pull request merged**
