### PR TITLE
Create evan-digital-literacy-takeaway.md

### PR DESCRIPTION
**Pull request by ezehnal**

### CODE REVIEW

**Comment by brookeabunnell** [comment]
@ezehnal - I was glad to see someone write about the Build-Measure-Learn loop! This concept is so simple (only three steps!) yet somehow encompasses such key elements of the development process. I wonder how much time teams should spend in each cycle of the loop. I'm sure it depends on the project, but it would be interesting to know. 

Prior to business school, I consulted on a few large ERP implementations (SAP and Oracle). During those projects, it felt like we were in the Build stage FOREVER. Much of this was requirements gathering... I thought we would never move on to testing. I always enjoyed the Measure stage of projects because we could finally bring users in to see how they would respond to a product. It was always surprising to see what they would do / figure out / get confused by / etc. When you're so close to it for so long, it's hard to see it objectively!

**Comment by mlong505** [comment]
Great graphic, Evan :+1:. I wish more non-tech organizations used a Build-Measure-Learn model. I feel like a lot of the team-based builds of excel models that I have done in the past are not that dissimilar from what developers do, except that the review process goes through a senior manager rather than a group of users. I would like to bring a little agile project management to my next job.

**Comment by chencbs** [comment]
@ezehnal Do you have any info on how frequently a software company should be implementing this Build-Measure-Learn cycle (weekly releases, monthly releases, etc)? I would think there's some point of diminishing returns when it gets annoying to the users - Windows Updates for example.

**Comment by idimkova** [comment]
Great question @ezehnal!  I just read through a couple of articles on the issue of how frequently companies should be implementing the cycle and it seems that the decision is driven by a few different factors, with one of the most important ones being the maturity of the company.  If it's very young, some founders recommend pushing releases every few weeks.  With companies who are further along, some experts advise against frequent releases to the public due to some of the the concerns you brought up.

**Comment by ezehnal** [comment]
Great questions team - the answer below should provide a better idea as to what the tenor of a Build-Measure-Learn cycle should look like! I've also added this commentary to the markup file.

"With respect to how long a Build-Measure-Learn cycle should take, it can depend on the relevant product, service, or feature, but generally more is better. The sources I have found describe the Build-Measure-Learn tenor as as little as 1 or 2 weeks for smaller features or leaner organizations, or as long as 2 months for larger organizations. More is better, and to the extent you can roll out and use Build-Measure-Learn on smaller parts of a bigger development cycle you may see even more learning benefit."

Any other comments before this gets :ship:'d? @mlong505 @brookeabunnell @idimkova @chencbs 

Cheers,
Evan

**Comment by chencbs** [comment]
LGTM :+1:

**Pull request merged**
